

export const MENU_SEED = [
  // ---- Account ----------------------------------------------------------
 { key: "accounting", name: "Accounting", parentKey: null, menuType: "group", icon: null, order: 10 },
  {
    key: "general_ledger",
    name: "General Ledger",
    parentKey: "accounting",
    menuType: "item",
    route: "/reports/general_ledger",
    component: "ReportPage",
    icon: "FileText",
    order: 10,
  },
  {
    key: "trial_balance",
    name: "Trial Balance",
    parentKey: "accounting",
    menuType: "item",
    route: "/reports/trial_balance",
    component: "ReportPage",
    icon: "FileText",
    order: 20,
  },
  {
    key: "accounts_receivable",
    name: "Accounts Receivable",
    parentKey: "accounting",
    menuType: "item",
    route: "/reports/accounts_receivable",
    component: "ReportPage",
    icon: "FileText",
    order: 30,
  },
  {
    key: "accounts_payable",
    name: "Accounts Payable",
    parentKey: "accounting",
    menuType: "item",
    route: "/reports/accounts_payable",
    component: "ReportPage",
    icon: "FileText",
    order: 40,
  },
  {
    key: "customer_aging",
    name: "Customer Aging",
    parentKey: "accounting",
    menuType: "item",
    route: "/reports/customer_aging",
    component: "ReportPage",
    icon: "FileText",
    order: 50,
  },
  {
    key: "vendor_aging",
    name: "Vendor Aging",
    parentKey: "accounting",
    menuType: "item",
    route: "/reports/vendor_aging",
    component: "ReportPage",
    icon: "FileText",
    order: 60,
  },

  // ---- Sales --------------------------------------------------------------
  { key: "sales", name: "Sales", parentKey: null, menuType: "group", icon: null, order: 20 },
  {
    key: "item_wise_sale",
    name: "Item Wise Sale",
    displayName: "Items Wise Sale",
    parentKey: "sales",
    menuType: "item",
    route: "/reports/item_wise_sale",
    component: "ReportPage",
    icon: "FileText",
    order: 10,
  },
  {
    key: "customer_wise_sale",
    name: "Customer Wise Sale",
    parentKey: "sales",
    menuType: "item",
    route: "/reports/customer_wise_sale",
    component: "ReportPage",
    icon: "FileText",
    order: 20,
  },
  {
    key: "top_items_sales",
    name: "Top Items Sales",
    parentKey: "sales",
    menuType: "item",
    route: "/reports/top_items_sales",
    component: "ReportPage",
    icon: "FileText",
    order: 30,
  },
  {
    key: "customer_item_wise_sale",
    name: "Customer Item Wise Sale",
    displayName: "Customer Items Wise Sale",
    parentKey: "sales",
    menuType: "item",
    route: "/reports/customer_item_wise_sale",
    component: "ReportPage",
    icon: "FileText",
    order: 40,
  },

  // ---- Purchases ------------------------------------------------------------
  { key: "purchases", name: "Purchases", parentKey: null, menuType: "group", icon: null, order: 30 },
  {
    key: "item_wise_purchase",
    name: "Item Wise Purchase",
    displayName: "Items Wise Purchase",
    parentKey: "purchases",
    menuType: "item",
    route: "/reports/item_wise_purchase",
    component: "ReportPage",
    icon: "FileText",
    order: 10,
  },
  {
    key: "vendor_wise_purchase",
    name: "Vendor Wise Purchase",
    parentKey: "purchases",
    menuType: "item",
    route: "/reports/vendor_wise_purchase",
    component: "ReportPage",
    icon: "FileText",
    order: 20,
  },

  // ---- Administration ---------------------------------------------------
  { key: "administration", name: "Administration", parentKey: null, menuType: "group", icon: null, order: 40 },
  {
    key: "user_access",
    name: "User Access",
    parentKey: "administration",
    menuType: "item",
    route: "/users",
    component: "UserManagement",
    icon: "Users",
    order: 10,
  },
  {
    key: "role_management",
    name: "Role Management",
    parentKey: "administration",
    menuType: "item",
    route: "/roles",
    component: "RoleManagement",
    icon: "ShieldCheck",
    order: 20,
  },
];

// Report menu items are exactly the leaf items whose key matches a report
// key from src/lib/reports.js (menuType 'item' with a /reports/:key route).
export const REPORT_MENU_KEYS = MENU_SEED.filter((m) => m.route?.startsWith("/reports/")).map((m) => m.key);
